"""Core Constants and Enumerations"""
from enum import Enum

class TaskState(str, Enum):
    PENDING = "PENDING"
    SCHEDULED = "SCHEDULED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"
    UPSTREAM_FAILED = "UPSTREAM_FAILED"

class PipelineState(str, Enum):
    INACTIVE = "INACTIVE"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    PARTIALLY_FAILED = "PARTIALLY_FAILED"

class ExecutionMode(str, Enum):
    BATCH = "BATCH"
    STREAMING = "STREAMING"
    MICRO_BATCH = "MICRO_BATCH"
    HYBRID = "HYBRID"

class TriggerType(str, Enum):
    MANUAL = "MANUAL"
    CRON = "CRON"
    INTERVAL = "INTERVAL"
    WEBHOOK = "WEBHOOK"
    EVENT = "EVENT"

class ConnectorType(str, Enum):
    POSTGRESQL = "POSTGRESQL"
    MYSQL = "MYSQL"
    KAFKA = "KAFKA"
    S3_PARQUET = "S3_PARQUET"
    GCS = "GCS"
    CLICKHOUSE = "CLICKHOUSE"
    SNOWFLAKE = "SNOWFLAKE"
    ELASTICSEARCH = "ELASTICSEARCH"
    REST_API = "REST_API"
    WEBHOOK = "WEBHOOK"
    LOCAL_FILE = "LOCAL_FILE"

class TransformType(str, Enum):
    SQL_DUCKDB = "SQL_DUCKDB"
    POLARS_LAZY = "POLARS_LAZY"
    STREAM_WINDOW = "STREAM_WINDOW"
    PYTHON_UDF = "PYTHON_UDF"
    DATA_CLEANING = "DATA_CLEANING"

class SchemaType(str, Enum):
    JSON_SCHEMA = "JSON_SCHEMA"
    APACHE_AVRO = "APACHE_AVRO"
    PROTOBUF = "PROTOBUF"

class CompatibilityLevel(str, Enum):
    NONE = "NONE"
    BACKWARD = "BACKWARD"
    FORWARD = "FORWARD"
    FULL = "FULL"

DEFAULT_RETRY_LIMIT = 3
DEFAULT_RETRY_DELAY_SECONDS = 5.0
DEFAULT_TASK_TIMEOUT_SECONDS = 3600
DEFAULT_WORKER_CONCURRENCY = 16
DEFAULT_BATCH_SIZE = 10000
